version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mks-backend-challenge
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
